# <center> $\text{INTRODUCCIÓN A PYTHON}$ </center>

## Característica

 - Es un lenguaje interpretado o interprete y de alto nivel.

- Soporta 4 paradigmas de programación:
    - paradigma por procedimientos o paradigma imperativo 


    - paradigma declarativo


    - paradigma funcional


    - paradigma orientado a objetos



### Ejemplos de paradigmas

#### Paradigma declarativo

In [4]:
import numpy as np

#### paradigma por procedimientos o paradigma imperativo

In [5]:
lista = [1,2,3,4,5] 
for i in lista: 
    print(i)

1
2
3
4
5


#### paradigma funcional

In [6]:
def sumar(x, y):
    return x + y

In [7]:
sumar(1, 2)

3

In [8]:
suma = lambda x, y: x + y

In [9]:
print(suma(2, 3))

5


#### paradigma orientado a objetos

In [10]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def saludar(self):
        print("Hola, soy {} y tengo {} años".format(self.nombre, self.edad))




In [11]:
p1 = Persona("Juan", 25)
p1.saludar()

Hola, soy Juan y tengo 25 años


## Tipos de variables

    - float
    - int
    - String
    - Listas
    - Tuplas
    - Diccionario

#### Float o flotentes

In [12]:
x=3.999999999999
type(x)

float

#### int o enteros

In [13]:
x=2
type(x)

int

#### String

In [14]:
x="Hola mundo"
type(x)

str

#### Lista

In [21]:
x=[1,2,3,4,4]
type(x)

list

In [22]:
x

[1, 2, 3, 4, 4]

In [23]:
x[4]=5

In [24]:
x

[1, 2, 3, 4, 5]

In [14]:
x[5]=6

IndexError: list assignment index out of range

In [15]:
x[4]=5

In [16]:
x

[1, 2, 3, 4, 5]

#### Tupla

In [25]:
x=(1,2,3,4,4)
type(x)

tuple

In [19]:
x[0]

1

In [27]:
x[5]=5

TypeError: 'tuple' object does not support item assignment

In [18]:
x[5]=6

TypeError: 'tuple' object does not support item assignment

In [22]:
x[4]=5

TypeError: 'tuple' object does not support item assignment

In [23]:
x

(1, 2, 3, 4, 4)

#### Diccionario

In [24]:
x={"1":1,"2":2}
type(x)

dict

In [25]:
x

{'1': 1, '2': 2}

In [26]:
x["1"]

1

In [27]:
x["3"]=3

In [28]:
x

{'1': 1, '2': 2, '3': 3}

In [3]:
type("Hola mi nombre es tal".upper())

str

In [29]:
pr=dict()

In [30]:
pr

{}

In [31]:
pr["nombre"]="Carlos"

In [32]:
pr

{'nombre': 'Carlos'}

In [34]:
x=np.array([])

In [35]:
x

array([], dtype=float64)

In [37]:
x

4889468156165151651561651651651651651515161115

In [38]:
x=[]

In [39]:
x=list()

In [40]:
x.append(1)

In [70]:
x=[1,2,3,4]

In [72]:
x=[[1,2,3],
   [4,5,6],
   [7,8,9]]

In [74]:
x=(1,2,3,4)

In [75]:
x=list(x)

In [76]:
x

[1, 2, 3, 4]

In [60]:
for i in range(1,100,0.5):

        x.append(i)
    

TypeError: 'float' object cannot be interpreted as an integer

In [47]:
x=[]

In [50]:
np.array(range(1,100+1))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [48]:
x.append(5)

In [49]:
x

[5]

In [67]:
x=np.linspace(1,100,10000)

In [66]:
np.array(range(1,100,4))

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [78]:
x=np.zeros(100)

In [79]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
x[0]=1

In [81]:
x

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [94]:
7%2

1

In [107]:
x=[]

In [108]:
for i in range(1,101):
    if i%2==0:
        x.append(i)
print(x)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [104]:
x=[ i for i in range(1,101) if  i%2==0]

In [106]:
print(x)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [117]:
8%3

2

In [129]:
x=dict()
s=0
for i in range(1,101):

    if i%2==0:
        x[s]=i
        s=s+1

In [130]:
x[0]

2

In [131]:
x

{0: 2,
 1: 4,
 2: 6,
 3: 8,
 4: 10,
 5: 12,
 6: 14,
 7: 16,
 8: 18,
 9: 20,
 10: 22,
 11: 24,
 12: 26,
 13: 28,
 14: 30,
 15: 32,
 16: 34,
 17: 36,
 18: 38,
 19: 40,
 20: 42,
 21: 44,
 22: 46,
 23: 48,
 24: 50,
 25: 52,
 26: 54,
 27: 56,
 28: 58,
 29: 60,
 30: 62,
 31: 64,
 32: 66,
 33: 68,
 34: 70,
 35: 72,
 36: 74,
 37: 76,
 38: 78,
 39: 80,
 40: 82,
 41: 84,
 42: 86,
 43: 88,
 44: 90,
 45: 92,
 46: 94,
 47: 96,
 48: 98,
 49: 100}

In [145]:
x="Mario"

In [146]:
x=x+"Montero"

In [147]:
x

'MarioMontero'

In [152]:
x.replace("a","")

'MrioMontero'

In [153]:
"Mi nombre es {} y tengo {} años".format("Jose","22")

'Mi nombre es Jose y tengo 22 años'

In [158]:
"""Hola, mi nombre es {}.
Trabajo en {}
y estudio en {}""".format("Mario", "K", "Universidad de Atlántico").
    

Object `join` not found.
