# <center> $\text{INTRODUCCIÓN A PYTHON}$ </center>

## Característica

 - Es un lenguaje interpretado o interprete y de alto nivel.

- Soporta 4 paradigmas de programación:
    - paradigma por procedimientos o paradigma imperativo 


    - paradigma declarativo


    - paradigma funcional


    - paradigma orientado a objetos



### Ejemplos de paradigmas

#### Paradigma declarativo

In [2]:
import numpy as np

#### paradigma por procedimientos o paradigma imperativo

In [5]:
lista = [1,2,3,4,5] 
for i in lista: 
    print(i)

1
2
3
4
5


#### paradigma funcional

In [6]:
def sumar(x, y):
    return x + y

In [7]:
sumar(1, 2)

3

In [8]:
suma = lambda x, y: x + y

In [9]:
print(suma(2, 3))

5


#### paradigma orientado a objetos

In [10]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def saludar(self):
        print("Hola, soy {} y tengo {} años".format(self.nombre, self.edad))




In [11]:
p1 = Persona("Juan", 25)
p1.saludar()

Hola, soy Juan y tengo 25 años


## Tipos de variables

    - float
    - int
    - String
    - Listas
    - Tuplas
    - Diccionario

#### Float o flotentes

In [12]:
x=3.999999999999
type(x)

float

#### int o enteros

In [13]:
x=2
type(x)

int

#### String

In [14]:
x="Hola mundo"
type(x)

str

#### Lista

In [21]:
x=[1,2,3,4,4]
type(x)

list

In [22]:
x

[1, 2, 3, 4, 4]

In [23]:
x[4]=5

In [24]:
x

[1, 2, 3, 4, 5]

In [14]:
x[5]=6

IndexError: list assignment index out of range

In [15]:
x[4]=5

In [16]:
x

[1, 2, 3, 4, 5]

#### Tupla

In [25]:
x=(1,2,3,4,4)
type(x)

tuple

In [19]:
x[0]

1

In [27]:
x[5]=5

TypeError: 'tuple' object does not support item assignment

In [18]:
x[5]=6

TypeError: 'tuple' object does not support item assignment

In [22]:
x[4]=5

TypeError: 'tuple' object does not support item assignment

In [23]:
x

(1, 2, 3, 4, 4)

#### Diccionario

In [24]:
x={"1":1,"2":2}
type(x)

dict

In [25]:
x

{'1': 1, '2': 2}

In [26]:
x["1"]

1

In [27]:
x["3"]=3

In [28]:
x

{'1': 1, '2': 2, '3': 3}

In [3]:
type("Hola mi nombre es tal".upper())

str

In [29]:
pr=dict()

In [30]:
pr

{}

In [31]:
pr["nombre"]="Carlos"

In [32]:
pr

{'nombre': 'Carlos'}

In [34]:
x=np.array([])

In [35]:
x

array([], dtype=float64)

In [37]:
x

4889468156165151651561651651651651651515161115

In [38]:
x=[]

In [39]:
x=list()

In [40]:
x.append(1)

In [70]:
x=[1,2,3,4]

In [72]:
x=[[1,2,3],
   [4,5,6],
   [7,8,9]]

In [74]:
x=(1,2,3,4)

In [75]:
x=list(x)

In [76]:
x

[1, 2, 3, 4]

In [60]:
for i in range(1,100,0.5):

        x.append(i)
    

TypeError: 'float' object cannot be interpreted as an integer

In [47]:
x=[]

In [50]:
np.array(range(1,100+1))

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [48]:
x.append(5)

In [49]:
x

[5]

In [67]:
x=np.linspace(1,100,10000)

In [66]:
np.array(range(1,100,4))

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49, 53, 57, 61, 65,
       69, 73, 77, 81, 85, 89, 93, 97])

In [78]:
x=np.zeros(100)

In [79]:
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
x[0]=1

In [81]:
x

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [94]:
7%2

1

In [107]:
x=[]

In [108]:
for i in range(1,101):
    if i%2==0:
        x.append(i)
print(x)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [104]:
x=[ i for i in range(1,101) if  i%2==0]

In [106]:
print(x)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [117]:
8%3

2

In [129]:
x=dict()
s=0
for i in range(1,101):

    if i%2==0:
        x[s]=i
        s=s+1

In [130]:
x[0]

2

In [131]:
x

{0: 2,
 1: 4,
 2: 6,
 3: 8,
 4: 10,
 5: 12,
 6: 14,
 7: 16,
 8: 18,
 9: 20,
 10: 22,
 11: 24,
 12: 26,
 13: 28,
 14: 30,
 15: 32,
 16: 34,
 17: 36,
 18: 38,
 19: 40,
 20: 42,
 21: 44,
 22: 46,
 23: 48,
 24: 50,
 25: 52,
 26: 54,
 27: 56,
 28: 58,
 29: 60,
 30: 62,
 31: 64,
 32: 66,
 33: 68,
 34: 70,
 35: 72,
 36: 74,
 37: 76,
 38: 78,
 39: 80,
 40: 82,
 41: 84,
 42: 86,
 43: 88,
 44: 90,
 45: 92,
 46: 94,
 47: 96,
 48: 98,
 49: 100}

In [145]:
x="Mario"

In [146]:
x=x+"Montero"

In [147]:
x

'MarioMontero'

In [152]:
x.replace("a","")

'MrioMontero'

In [153]:
"Mi nombre es {} y tengo {} años".format("Jose","22")

'Mi nombre es Jose y tengo 22 años'

In [1]:
"""Hola, mi nombre es {}.
Trabajo en {}
y estudio en {}""".format("Mario", "K", "Universidad de Atlántico")
    

'Hola, mi nombre es Mario.\nTrabajo en K\ny estudio en Universidad de Atlántico'

In [ ]:
if elif else while 

In [ ]:
if (condicion):
    (Algoritmo)

In [6]:
2!=4

True

In [7]:
1>4

False

In [8]:
4>1

True

In [10]:
4<=4

True

In [13]:
x=np.linspace(1,100,1000)

In [14]:
x

array([  1.        ,   1.0990991 ,   1.1981982 ,   1.2972973 ,
         1.3963964 ,   1.4954955 ,   1.59459459,   1.69369369,
         1.79279279,   1.89189189,   1.99099099,   2.09009009,
         2.18918919,   2.28828829,   2.38738739,   2.48648649,
         2.58558559,   2.68468468,   2.78378378,   2.88288288,
         2.98198198,   3.08108108,   3.18018018,   3.27927928,
         3.37837838,   3.47747748,   3.57657658,   3.67567568,
         3.77477477,   3.87387387,   3.97297297,   4.07207207,
         4.17117117,   4.27027027,   4.36936937,   4.46846847,
         4.56756757,   4.66666667,   4.76576577,   4.86486486,
         4.96396396,   5.06306306,   5.16216216,   5.26126126,
         5.36036036,   5.45945946,   5.55855856,   5.65765766,
         5.75675676,   5.85585586,   5.95495495,   6.05405405,
         6.15315315,   6.25225225,   6.35135135,   6.45045045,
         6.54954955,   6.64864865,   6.74774775,   6.84684685,
         6.94594595,   7.04504505,   7.14414414,   7.24

In [19]:
x1=[]
x2=[]
s=0
while s<=len(x)-1:
    if x[s]<50:
        x1.append(x[s])
    else:
        x2.append(x[s])
    s+=1
    

In [20]:
x1

[1.0,
 1.0990990990990992,
 1.1981981981981982,
 1.2972972972972974,
 1.3963963963963963,
 1.4954954954954955,
 1.5945945945945947,
 1.6936936936936937,
 1.7927927927927927,
 1.8918918918918919,
 1.990990990990991,
 2.09009009009009,
 2.1891891891891895,
 2.288288288288288,
 2.3873873873873874,
 2.4864864864864864,
 2.5855855855855854,
 2.684684684684685,
 2.7837837837837838,
 2.8828828828828827,
 2.981981981981982,
 3.081081081081081,
 3.18018018018018,
 3.279279279279279,
 3.3783783783783785,
 3.4774774774774775,
 3.5765765765765765,
 3.675675675675676,
 3.774774774774775,
 3.873873873873874,
 3.972972972972973,
 4.072072072072072,
 4.171171171171171,
 4.27027027027027,
 4.36936936936937,
 4.468468468468469,
 4.5675675675675675,
 4.666666666666666,
 4.7657657657657655,
 4.864864864864865,
 4.963963963963964,
 5.063063063063063,
 5.162162162162162,
 5.261261261261262,
 5.36036036036036,
 5.45945945945946,
 5.558558558558558,
 5.657657657657658,
 5.756756756756757,
 5.8558558558558556,

In [24]:
x[999]

100.0

In [22]:
len(x)

1000

In [25]:
for i in range(len(x)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [37]:
x1=[]
x2=[]
x3=[]
s=0
while s<=len(x)-1:
    if x[s]<25:
        x1.append(x[s])
    elif x[s]>=25 and x[s]<75:
        x2.append(x[s])
    else:
        x3.append(x[s])
        
    s+=1

In [33]:
True and True

True

In [31]:
False or False

False

In [35]:
x1

[1.0,
 1.0990990990990992,
 1.1981981981981982,
 1.2972972972972974,
 1.3963963963963963,
 1.4954954954954955,
 1.5945945945945947,
 1.6936936936936937,
 1.7927927927927927,
 1.8918918918918919,
 1.990990990990991,
 2.09009009009009,
 2.1891891891891895,
 2.288288288288288,
 2.3873873873873874,
 2.4864864864864864,
 2.5855855855855854,
 2.684684684684685,
 2.7837837837837838,
 2.8828828828828827,
 2.981981981981982,
 3.081081081081081,
 3.18018018018018,
 3.279279279279279,
 3.3783783783783785,
 3.4774774774774775,
 3.5765765765765765,
 3.675675675675676,
 3.774774774774775,
 3.873873873873874,
 3.972972972972973,
 4.072072072072072,
 4.171171171171171,
 4.27027027027027,
 4.36936936936937,
 4.468468468468469,
 4.5675675675675675,
 4.666666666666666,
 4.7657657657657655,
 4.864864864864865,
 4.963963963963964,
 5.063063063063063,
 5.162162162162162,
 5.261261261261262,
 5.36036036036036,
 5.45945945945946,
 5.558558558558558,
 5.657657657657658,
 5.756756756756757,
 5.8558558558558556,

In [38]:
x2

[25.08108108108108,
 25.18018018018018,
 25.27927927927928,
 25.37837837837838,
 25.47747747747748,
 25.576576576576578,
 25.675675675675677,
 25.774774774774777,
 25.873873873873872,
 25.972972972972972,
 26.07207207207207,
 26.17117117117117,
 26.27027027027027,
 26.36936936936937,
 26.46846846846847,
 26.56756756756757,
 26.666666666666668,
 26.765765765765767,
 26.864864864864867,
 26.963963963963963,
 27.063063063063062,
 27.16216216216216,
 27.26126126126126,
 27.36036036036036,
 27.45945945945946,
 27.55855855855856,
 27.65765765765766,
 27.756756756756758,
 27.855855855855857,
 27.954954954954957,
 28.054054054054053,
 28.153153153153152,
 28.25225225225225,
 28.35135135135135,
 28.45045045045045,
 28.54954954954955,
 28.64864864864865,
 28.74774774774775,
 28.846846846846848,
 28.945945945945947,
 29.045045045045047,
 29.144144144144143,
 29.243243243243242,
 29.34234234234234,
 29.44144144144144,
 29.54054054054054,
 29.63963963963964,
 29.73873873873874,
 29.83783783783784,


In [39]:
x3

[75.02702702702703,
 75.12612612612612,
 75.22522522522523,
 75.32432432432432,
 75.42342342342343,
 75.52252252252252,
 75.62162162162163,
 75.72072072072072,
 75.81981981981983,
 75.91891891891892,
 76.01801801801801,
 76.11711711711712,
 76.21621621621621,
 76.31531531531532,
 76.41441441441441,
 76.51351351351352,
 76.61261261261261,
 76.71171171171171,
 76.8108108108108,
 76.90990990990991,
 77.009009009009,
 77.10810810810811,
 77.2072072072072,
 77.30630630630631,
 77.4054054054054,
 77.50450450450451,
 77.6036036036036,
 77.70270270270271,
 77.8018018018018,
 77.90090090090091,
 78.0,
 78.0990990990991,
 78.1981981981982,
 78.29729729729729,
 78.3963963963964,
 78.49549549549549,
 78.5945945945946,
 78.69369369369369,
 78.7927927927928,
 78.89189189189189,
 78.990990990991,
 79.09009009009009,
 79.1891891891892,
 79.28828828828829,
 79.38738738738739,
 79.48648648648648,
 79.58558558558559,
 79.68468468468468,
 79.78378378378379,
 79.88288288288288,
 79.98198198198199,
 80.0810

In [40]:
x=input()

4


In [41]:
x

'4'

In [44]:
x=float(x)

In [45]:
x

4.0

In [48]:
def suma(a,b):
    h=a+b
    return h

In [52]:
a=float(input("Introduzca a: "))
b=float(input("Introduzca b: "))
x=a
y=b
if x==y:
    h=suma(a,b)
    msg="la variable {} es igual a {}, entonces se realizo una suma".format(a,b)
elif x<y:
    h=a*b
    msg="la variable {} es menor a {}, entonces se realizo una multiplicación".format(a,b)
else:
    h=a/b
    msg="la variable {} es mayor a {}, entonces se realizo una división".format(a,b)
print(h,msg)

Introduzca a: 10
Introduzca b: 5
2.0 la variable 10.0 es mayor a 5.0, entonces se realizo una división


# Ejercicio
Los alumnos de un curso se han dividido en dos grupos A y B de acuerdo al sexo y el nombre. El grupo A esta formado por las mujeres con un nombre anterior a la M y los hombres con un nombre posterior a la N y el grupo B por el resto. Escribir un programa que pregunte al usuario su nombre y sexo, y muestre por pantalla el grupo que le corresponde.

In [53]:
nombre=input("¿Cómo te llamas? ")
genero=input("¿Cual es tu sexo (M o H)? ")

    

¿Cómo te llamas?Mario
¿Cual es tu sexo (M o H)?H


In [64]:
nombre[0].lower() <"n" 

True

In [68]:
not True

False

In [1]:
lista=[[1,2,3,4],[1,2,3,4]]

In [ ]:
lista.

In [3]:
lista=np.array(lista)

In [7]:
lista.min()


1

In [8]:
import pandas as pd

In [11]:
datos=pd.DataFrame()


In [13]:
datos["id"]=np.array(range(1,100))

In [22]:
datos

id
0    1
1    2
2    3
3    4
4    5
..  ..
94  95
95  96
96  97
97  98
98  99

[99 rows x 1 columns]